Universe = vanilla

executable = /home/hongyul/AMA/wiki.sh
arguments = 0
output = /home/hongyul/condor/condor0.job.out
log = /tmp/hongyul0.job.log
error = /home/hongyul/condor/condor0.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 1
output = /home/hongyul/condor/condor1.job.out
log = /tmp/hongyul1.job.log
error = /home/hongyul/condor/condor1.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 2
output = /home/hongyul/condor/condor2.job.out
log = /tmp/hongyul2.job.log
error = /home/hongyul/condor/condor2.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 3
output = /home/hongyul/condor/condor3.job.out
log = /tmp/hongyul3.job.log
error = /home/hongyul/condor/condor3.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 4
output = /home/hongyul/condor/condor4.job.out
log = /tmp/hongyul4.job.log
error = /home/hongyul/condor/condor4.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 5
output = /home/hongyul/condor/condor5.job.out
log = /tmp/hongyul5.job.log
error = /home/hongyul/condor/condor5.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 6
output = /home/hongyul/condor/condor6.job.out
log = /tmp/hongyul6.job.log
error = /home/hongyul/condor/condor6.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 7
output = /home/hongyul/condor/condor7.job.out
log = /tmp/hongyul7.job.log
error = /home/hongyul/condor/condor7.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 8
output = /home/hongyul/condor/condor8.job.out
log = /tmp/hongyul8.job.log
error = /home/hongyul/condor/condor8.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 9
output = /home/hongyul/condor/condor9.job.out
log = /tmp/hongyul9.job.log
error = /home/hongyul/condor/condor9.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 10
output = /home/hongyul/condor/condor10.job.out
log = /tmp/hongyul10.job.log
error = /home/hongyul/condor/condor10.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 11
output = /home/hongyul/condor/condor11.job.out
log = /tmp/hongyul11.job.log
error = /home/hongyul/condor/condor11.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 12
output = /home/hongyul/condor/condor12.job.out
log = /tmp/hongyul12.job.log
error = /home/hongyul/condor/condor12.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 13
output = /home/hongyul/condor/condor13.job.out
log = /tmp/hongyul13.job.log
error = /home/hongyul/condor/condor13.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 14
output = /home/hongyul/condor/condor14.job.out
log = /tmp/hongyul14.job.log
error = /home/hongyul/condor/condor14.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 15
output = /home/hongyul/condor/condor15.job.out
log = /tmp/hongyul15.job.log
error = /home/hongyul/condor/condor15.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 16
output = /home/hongyul/condor/condor16.job.out
log = /tmp/hongyul16.job.log
error = /home/hongyul/condor/condor16.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 17
output = /home/hongyul/condor/condor17.job.out
log = /tmp/hongyul17.job.log
error = /home/hongyul/condor/condor17.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 18
output = /home/hongyul/condor/condor18.job.out
log = /tmp/hongyul18.job.log
error = /home/hongyul/condor/condor18.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 19
output = /home/hongyul/condor/condor19.job.out
log = /tmp/hongyul19.job.log
error = /home/hongyul/condor/condor19.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 20
output = /home/hongyul/condor/condor20.job.out
log = /tmp/hongyul20.job.log
error = /home/hongyul/condor/condor20.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 21
output = /home/hongyul/condor/condor21.job.out
log = /tmp/hongyul21.job.log
error = /home/hongyul/condor/condor21.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 22
output = /home/hongyul/condor/condor22.job.out
log = /tmp/hongyul22.job.log
error = /home/hongyul/condor/condor22.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 23
output = /home/hongyul/condor/condor23.job.out
log = /tmp/hongyul23.job.log
error = /home/hongyul/condor/condor23.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 24
output = /home/hongyul/condor/condor24.job.out
log = /tmp/hongyul24.job.log
error = /home/hongyul/condor/condor24.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 25
output = /home/hongyul/condor/condor25.job.out
log = /tmp/hongyul25.job.log
error = /home/hongyul/condor/condor25.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 26
output = /home/hongyul/condor/condor26.job.out
log = /tmp/hongyul26.job.log
error = /home/hongyul/condor/condor26.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 27
output = /home/hongyul/condor/condor27.job.out
log = /tmp/hongyul27.job.log
error = /home/hongyul/condor/condor27.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 28
output = /home/hongyul/condor/condor28.job.out
log = /tmp/hongyul28.job.log
error = /home/hongyul/condor/condor28.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 29
output = /home/hongyul/condor/condor29.job.out
log = /tmp/hongyul29.job.log
error = /home/hongyul/condor/condor29.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 30
output = /home/hongyul/condor/condor30.job.out
log = /tmp/hongyul30.job.log
error = /home/hongyul/condor/condor30.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 31
output = /home/hongyul/condor/condor31.job.out
log = /tmp/hongyul31.job.log
error = /home/hongyul/condor/condor31.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 32
output = /home/hongyul/condor/condor32.job.out
log = /tmp/hongyul32.job.log
error = /home/hongyul/condor/condor32.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 33
output = /home/hongyul/condor/condor33.job.out
log = /tmp/hongyul33.job.log
error = /home/hongyul/condor/condor33.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 34
output = /home/hongyul/condor/condor34.job.out
log = /tmp/hongyul34.job.log
error = /home/hongyul/condor/condor34.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 35
output = /home/hongyul/condor/condor35.job.out
log = /tmp/hongyul35.job.log
error = /home/hongyul/condor/condor35.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 36
output = /home/hongyul/condor/condor36.job.out
log = /tmp/hongyul36.job.log
error = /home/hongyul/condor/condor36.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 37
output = /home/hongyul/condor/condor37.job.out
log = /tmp/hongyul37.job.log
error = /home/hongyul/condor/condor37.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 38
output = /home/hongyul/condor/condor38.job.out
log = /tmp/hongyul38.job.log
error = /home/hongyul/condor/condor38.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 39
output = /home/hongyul/condor/condor39.job.out
log = /tmp/hongyul39.job.log
error = /home/hongyul/condor/condor39.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 40
output = /home/hongyul/condor/condor40.job.out
log = /tmp/hongyul40.job.log
error = /home/hongyul/condor/condor40.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 41
output = /home/hongyul/condor/condor41.job.out
log = /tmp/hongyul41.job.log
error = /home/hongyul/condor/condor41.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 42
output = /home/hongyul/condor/condor42.job.out
log = /tmp/hongyul42.job.log
error = /home/hongyul/condor/condor42.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 43
output = /home/hongyul/condor/condor43.job.out
log = /tmp/hongyul43.job.log
error = /home/hongyul/condor/condor43.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 44
output = /home/hongyul/condor/condor44.job.out
log = /tmp/hongyul44.job.log
error = /home/hongyul/condor/condor44.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 45
output = /home/hongyul/condor/condor45.job.out
log = /tmp/hongyul45.job.log
error = /home/hongyul/condor/condor45.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 46
output = /home/hongyul/condor/condor46.job.out
log = /tmp/hongyul46.job.log
error = /home/hongyul/condor/condor46.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 47
output = /home/hongyul/condor/condor47.job.out
log = /tmp/hongyul47.job.log
error = /home/hongyul/condor/condor47.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 48
output = /home/hongyul/condor/condor48.job.out
log = /tmp/hongyul48.job.log
error = /home/hongyul/condor/condor48.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 49
output = /home/hongyul/condor/condor49.job.out
log = /tmp/hongyul49.job.log
error = /home/hongyul/condor/condor49.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 50
output = /home/hongyul/condor/condor50.job.out
log = /tmp/hongyul50.job.log
error = /home/hongyul/condor/condor50.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 51
output = /home/hongyul/condor/condor51.job.out
log = /tmp/hongyul51.job.log
error = /home/hongyul/condor/condor51.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 52
output = /home/hongyul/condor/condor52.job.out
log = /tmp/hongyul52.job.log
error = /home/hongyul/condor/condor52.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 53
output = /home/hongyul/condor/condor53.job.out
log = /tmp/hongyul53.job.log
error = /home/hongyul/condor/condor53.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 54
output = /home/hongyul/condor/condor54.job.out
log = /tmp/hongyul54.job.log
error = /home/hongyul/condor/condor54.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 55
output = /home/hongyul/condor/condor55.job.out
log = /tmp/hongyul55.job.log
error = /home/hongyul/condor/condor55.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 56
output = /home/hongyul/condor/condor56.job.out
log = /tmp/hongyul56.job.log
error = /home/hongyul/condor/condor56.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 57
output = /home/hongyul/condor/condor57.job.out
log = /tmp/hongyul57.job.log
error = /home/hongyul/condor/condor57.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 58
output = /home/hongyul/condor/condor58.job.out
log = /tmp/hongyul58.job.log
error = /home/hongyul/condor/condor58.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 59
output = /home/hongyul/condor/condor59.job.out
log = /tmp/hongyul59.job.log
error = /home/hongyul/condor/condor59.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 60
output = /home/hongyul/condor/condor60.job.out
log = /tmp/hongyul60.job.log
error = /home/hongyul/condor/condor60.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 61
output = /home/hongyul/condor/condor61.job.out
log = /tmp/hongyul61.job.log
error = /home/hongyul/condor/condor61.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 62
output = /home/hongyul/condor/condor62.job.out
log = /tmp/hongyul62.job.log
error = /home/hongyul/condor/condor62.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 63
output = /home/hongyul/condor/condor63.job.out
log = /tmp/hongyul63.job.log
error = /home/hongyul/condor/condor63.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 64
output = /home/hongyul/condor/condor64.job.out
log = /tmp/hongyul64.job.log
error = /home/hongyul/condor/condor64.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 65
output = /home/hongyul/condor/condor65.job.out
log = /tmp/hongyul65.job.log
error = /home/hongyul/condor/condor65.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 66
output = /home/hongyul/condor/condor66.job.out
log = /tmp/hongyul66.job.log
error = /home/hongyul/condor/condor66.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 67
output = /home/hongyul/condor/condor67.job.out
log = /tmp/hongyul67.job.log
error = /home/hongyul/condor/condor67.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 68
output = /home/hongyul/condor/condor68.job.out
log = /tmp/hongyul68.job.log
error = /home/hongyul/condor/condor68.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 69
output = /home/hongyul/condor/condor69.job.out
log = /tmp/hongyul69.job.log
error = /home/hongyul/condor/condor69.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 70
output = /home/hongyul/condor/condor70.job.out
log = /tmp/hongyul70.job.log
error = /home/hongyul/condor/condor70.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 71
output = /home/hongyul/condor/condor71.job.out
log = /tmp/hongyul71.job.log
error = /home/hongyul/condor/condor71.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 72
output = /home/hongyul/condor/condor72.job.out
log = /tmp/hongyul72.job.log
error = /home/hongyul/condor/condor72.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 73
output = /home/hongyul/condor/condor73.job.out
log = /tmp/hongyul73.job.log
error = /home/hongyul/condor/condor73.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 74
output = /home/hongyul/condor/condor74.job.out
log = /tmp/hongyul74.job.log
error = /home/hongyul/condor/condor74.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 75
output = /home/hongyul/condor/condor75.job.out
log = /tmp/hongyul75.job.log
error = /home/hongyul/condor/condor75.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 76
output = /home/hongyul/condor/condor76.job.out
log = /tmp/hongyul76.job.log
error = /home/hongyul/condor/condor76.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 77
output = /home/hongyul/condor/condor77.job.out
log = /tmp/hongyul77.job.log
error = /home/hongyul/condor/condor77.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 78
output = /home/hongyul/condor/condor78.job.out
log = /tmp/hongyul78.job.log
error = /home/hongyul/condor/condor78.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 79
output = /home/hongyul/condor/condor79.job.out
log = /tmp/hongyul79.job.log
error = /home/hongyul/condor/condor79.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 80
output = /home/hongyul/condor/condor80.job.out
log = /tmp/hongyul80.job.log
error = /home/hongyul/condor/condor80.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 81
output = /home/hongyul/condor/condor81.job.out
log = /tmp/hongyul81.job.log
error = /home/hongyul/condor/condor81.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 82
output = /home/hongyul/condor/condor82.job.out
log = /tmp/hongyul82.job.log
error = /home/hongyul/condor/condor82.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 83
output = /home/hongyul/condor/condor83.job.out
log = /tmp/hongyul83.job.log
error = /home/hongyul/condor/condor83.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 84
output = /home/hongyul/condor/condor84.job.out
log = /tmp/hongyul84.job.log
error = /home/hongyul/condor/condor84.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 85
output = /home/hongyul/condor/condor85.job.out
log = /tmp/hongyul85.job.log
error = /home/hongyul/condor/condor85.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 86
output = /home/hongyul/condor/condor86.job.out
log = /tmp/hongyul86.job.log
error = /home/hongyul/condor/condor86.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 87
output = /home/hongyul/condor/condor87.job.out
log = /tmp/hongyul87.job.log
error = /home/hongyul/condor/condor87.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 88
output = /home/hongyul/condor/condor88.job.out
log = /tmp/hongyul88.job.log
error = /home/hongyul/condor/condor88.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 89
output = /home/hongyul/condor/condor89.job.out
log = /tmp/hongyul89.job.log
error = /home/hongyul/condor/condor89.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 90
output = /home/hongyul/condor/condor90.job.out
log = /tmp/hongyul90.job.log
error = /home/hongyul/condor/condor90.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 91
output = /home/hongyul/condor/condor91.job.out
log = /tmp/hongyul91.job.log
error = /home/hongyul/condor/condor91.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 92
output = /home/hongyul/condor/condor92.job.out
log = /tmp/hongyul92.job.log
error = /home/hongyul/condor/condor92.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 93
output = /home/hongyul/condor/condor93.job.out
log = /tmp/hongyul93.job.log
error = /home/hongyul/condor/condor93.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 94
output = /home/hongyul/condor/condor94.job.out
log = /tmp/hongyul94.job.log
error = /home/hongyul/condor/condor94.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 95
output = /home/hongyul/condor/condor95.job.out
log = /tmp/hongyul95.job.log
error = /home/hongyul/condor/condor95.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 96
output = /home/hongyul/condor/condor96.job.out
log = /tmp/hongyul96.job.log
error = /home/hongyul/condor/condor96.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 97
output = /home/hongyul/condor/condor97.job.out
log = /tmp/hongyul97.job.log
error = /home/hongyul/condor/condor97.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 98
output = /home/hongyul/condor/condor98.job.out
log = /tmp/hongyul98.job.log
error = /home/hongyul/condor/condor98.job.err
queue

executable = /home/hongyul/AMA/wiki.sh
arguments = 99
output = /home/hongyul/condor/condor99.job.out
log = /tmp/hongyul99.job.log
error = /home/hongyul/condor/condor99.job.err
queue

